### ISSUE TITLE
Complete Load Core Schema as Holons

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#112]
This completes the work begun under Issue #87 .

## Dependencies
Issue #103 

## Proposal
Load the MAP L0 Core Schema in a guest-side  function invoked from _load_core_schema_dance_.

- [x] Define L0 Value Types
- [x] Define L0 Property Types
- [x] Define L0 Collection Types
- [x] Define L0 Holon Types
- [x] Define L0 Relationship Types

#### Concrete Holon Types
- [x] SchemaType
- [x] HolonSpaceType

#### Abstract Holon Types

These serve as supertypes of the various concrete types of each flavor. They are needed as a place to tie Relationships (either as a Source or Target) shared by all descriptors of that flavor.
- [x] HolonType -- specifies that all HolonTypes (including itself) have PROPERTIES, SOURCE_FOR and DANCES relationships
- [x] DanceRequestType -- specifies the PROPERTIES, SOURCE_FOR and DANCES shared by all DanceRequestTypes
- [ ] DanceResponseType  -- specifies the PROPERTIES, SOURCE_FOR and DANCES shared by all DanceResponseTypes
- [ ] PropertyType -- specifies the PROPERTIES, SOURCE_FOR and DANCES shared by all PropertyTypes
- [ ] RelationshipType -- specifies the PROPERTIES, SOURCE_FOR and DANCES shared by all RelationshipTypes
- [ ] ValueType -- -- specifies the PROPERTIES, SOURCE_FOR and DANCES shared by all ValueTypes

#### Collection Types with max cardinality = 1  
- [x] HolonType 
- [x] TypeDescriptor 
- [ ] RelationshipType 
- [ ] PropertyType
- [ ] TargetCollectionType
- [ ] HolonSpace 
- [ ] SchemaType
- [ ] Holon
- [ ] Schema
- [ ] ValueType

#### Collection Types with max cardinality > 1  
- [ ] PropertyTypeList -- target of KEY_SPEC relationship
- [ ] PropertyTypes
- [ ] RelationshipTypes
- [ ] DanceTypes
- [ ] TypeDescriptors
- [ ] Holons

#### Define L0 Relationship Types

- [x] *COMPONENTS -> TypeDescriptors
- [x] COMPONENT_OF -> Schema
- [ ] *DANCES -> DanceTypes
- [ ] DANCE_OF -> HolonType
- [x] *DESCRIBED_BY -> HolonType
- [x] INSTANCES  -> TypeDescriptor
- [x] *IS_A  -> [TypeDescriptor, ValueType, HolonCollectionType]
- [x] HAS_SUBTYPE  -> [SchemaType, HolonType, PropertyType, RelationshipType,...]
- [x] *OWNED_BY -> HolonSpace
- [x] OWNS -> Holon
- [x] *PROPERTIES -> PropertyTypes
- [x] PROPERTY_OF -> HolonType
- [ ] SOURCE_TYPE -> TypeDescriptor
- [ ] TARGET_COLLECTION_TYPE -> HolonCollectionType
- [ ] TARGET_HOLON_TYPE -> HolonType
- [ ] TARGET_PROPERTY_TYPE  ->  PropertyType
- [ ] FOR_COLLECTION_TYPE ->

- [ ] COLLECTION_FOR -> RelationshipType
- [ ] HAS_INVERSE -> RelationshipType
- [ ] INVERSE_OF -> RelationshipType

## Tasks

- [x] Create separate `core_schema` crate with one .rs file for each base type
- [x] Define an umbrella CoreSchema enum that wraps all the other types
- [x] Each file defines for the enum for all core schema elements of that type
- [x] Each enum implements the SchemaNames Trait for itself
- [x] Move load_xxx_type functions to separate file (crate?) where xxx is each base type
- [x] Enhance get_core_value_type_descriptor_reference into general "lazy loader" for type definitions
     - generalize it to get_type_descriptor_reference
     - if not found in dance_state, try cache
     - if not found in cache, then invoke load_type_descriptor for the requested

- [x] Implement overall schema loader that pulls everything else in via lazy load
- [x] Define a separate issue to implement a json_adapters for core schema elements. See Issue #121.

**Comment by evomimic** [comment]
## Some Key Design Decisions

1.  Load of MetaDescriptors can be deferred to a later issue under the assumption that MetaDescriptors are NOT required to create descriptors in Rust (that's what the define_xxx functions are for).  MetaDescriptors are ONLY need to validate descriptor definitions and to support the HX of displaying, defining and updating types in the client. Therefore, tasks related for metadescriptors were moved from this issue to Issue #119.
2. _**Rust structures and methods should be defined for each Core Descriptor type.**_ Collectively, these objects and their associated functions define a descriptor-layer than can be implemented in Rust on the guest-side and Typescript on the client-side that make it easier to use and interact with descriptors.  Each can offer `into_holon` and `from_holon` methods for converting back and forth between their holonic representation. 
3. TypeDescriptor will be a Holon and not just a "header'" struct. Type objects (e.g., HolonTypes, PropertyTypes, etc.) will refer to their TypeDescriptor via TYPE_DESCRIPTOR relationship. Type_descriptor_name will be the key property for TypeDescriptor. The child descriptor will define the type_name.
4. **_Schema offers a flat type name space._**  Relationship names, property names, holon type names must all be unique with in a schema. This means, for example, the unique typename for authors is "AUTHORS"  instead of "(Book)-AUTHORS->(Person)".
5.  HolonCollectionDescriptors will be needed (and perhaps need to be _transient_ in the query layer). These descriptors specify whether the collection is ordered (i.e., vector), an unordered set (no duplicates), min/max cardinality, reference to TargetHolonType for the members of that collection
6. RelationshipDescriptors will be split and target info will be specified in a  HolonCollectionType descriptors 
7.  **_Key definitions will be represented as HolonCollections, not ValueType Arrays_**.  Specifically, a `PropertyDescriptorList` _CollectionType_ will be defined and a `KEY_SPEC` _RelationshipType_ that relates `HolonType` to `PropertyDescriptorList` collection.

**Comment by evomimic** [comment]
## Defer Type Creation to Avoid Cycles in Lazy Load Process
The lazy load strategy can result in infinite loops due to circular dependencies. For example,  If Z tries to lazy load Y, Y loads X, and X loads Z, the process will never terminate.

### Proposal:  

The basic idea is that when asking to lazy load a type, the default implementation of the  `lazy_get_core_type_definition` in the CoreSchemaNames trait needs to check if an attempt to load that type is already in process and, if so, return a "Deferred" indication. The calling function then needs to handle this in a way that ensures that whatever depended on the reference to the requested type can be _memoized_ so that it may be staged later and then continue with its own definition (in case the dependent type has a direct or indirect dependency on it). 

This begs the following questions:

1. How /where do we keep track of the "in-progress" type definitions?
2. How do we "memoize" delayed requests?
3. How do types proceed with their definition when they encounter a "delay"?
4. How do we ensure delayed actions happen?


For now this "memoizing" will be done in the form of a "warn" level trace message so I can better assess when / how frequently it is occurring.

If we assume that a reference to the staged_holon is only added to the dance_state AFTER it has been fully staged (i.e., AFTER all of its dependencies have been satisfied), then the presence of the reference in the dance_state means its staging is no longer in progress. So perhaps we could maintain a separate list of "in-progress" type definitions. The `lazy_get_core_type_definition`  should add its type to the "in-progress" list and the `add_reference_to_dance_state` (or a wrapper of that call) should remove the type from the "in-progress" list. 

But where do we maintain this list? The current definition of `TransientCollection` in the `DanceState` is not rich enough. Perhaps we could make `DanceState` a struct that contains BOTH `TransientCollection` AND an `in_progress` vector of _CoreSchemaTypeNames_?

TransientCollection has been defined as Vec of HolonReferences (with a keyed_index) under the assumption that the actual holon state is either Staged or Cached. But 

#### In the core_schema_types.rs file

- [ ] Enhance the default implementation of
