### ISSUE TITLE
Testable Holon Creation

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#36]
The goal of this story is to pull together various elements of the recent refactoring work, to deliver a "vertical slice" of functionality that provides an end-to-end test of holon creation. Starting with the bare minimum capabilities (defined below), this will create an expandable core that we can incrementally enhance.

### Minimum Capabilities

1. Create (undescribed) holons
2. Populate values for holons
3. Relate two holons via a single-valued relationship
4. Add holons to the HolonCollection associated with a multi-valued relationship

### Dependencies

- [x] Ability to Stage new (undescribed) holons
- [x] Ability to Populate property values for staged holons -- see Issue #71
- [x] CommitManager (or some container that "owns" staged holons prior to commit? (Issue #37)
- [x] Shared ownership model that allows mutation/checkout?
- [ ] Dance Request/Responses implemented for:
  - [x] HolonSpace: `get_all_holons` -- resolved via PR #67
  - [ ] HolonSpace: `get_holon_by_key`
  - [ ] HolonSpace: `get_holon_by_id`
  - [x] HolonSpace: `stage_new_holon` -- stages a new holon for building and committing -- resolved in Issue #63
  - [ ] FUTURE HolonSpace: `edit_holon` --  stages a new version of an existing holon for update, retaining the linkage to the holon version it is derived from
  - [ ] FUTURE Holon:Space: `clone_holon` -- -- stages a new holon by first copying it from an existing holon , without retaining predecessor linkage

  - [ ]  HolonSpace: `commit` -- commits all staged holons -- implemented in PR #67, enhanced via Issue #69
  - [x] Holon: with_property_values -- see Issue #71 
  - [ ] Holon: set_key_manually
  - [ ] Holon: add_related_holons -- native function implementation in Issue #57 
 
 
- [ ] Need MetaRelationshipDescriptor? to write the "SOURCE" and "TARGET"  smart links for the HOLONS relationship
- [x] Add the RelationshipTarget as the related holon target for an (undescribed) HolonRelationship.
- [x] Create a StagedCollection as part of a Many-valued RelationshipTarget
- [ ] Stage two additional holons, create HolonReferences for each, and add them to the StagedCollection
- [ ] Commit all staged changes
    - [ ] Ability to create SmartLink's from RelationshipMap    
    - [ ] Requires RelationshipDescriptor    
- [ ] Fetch all holons and print them out
- [ ] Format holon output as JSON?

### Load Core Schema Script

The basic idea is to try the approach, first defining all necessary descriptors, then wiring them together with relationships.

In load_core_schema() function:

- Create 

### Script
1. Stage a minimal schema    
     1. Stage (undescribed) HolonSpaceHolonDescriptor Holon and populate its properties
     2. Create (undescribed) HolonDescriptor Holon and populate its properties
     3. Create the MetaRelationshipDescriptor with SOURCE_HOLON_TYPE and TARGET_HOLON_TYPE relationships in its relationship_map
     4. Create HolonSpace-HOLONS->Holon RelationshipDescriptor Holon
2.  Commit staged holons
    1. Save the Holons as HolonNodes
    2. Save the RelationshipMap as SmartLinks

3. Get all Holons
    1. Output serialized holons

### Questions

1. Ownership of "StagedHolons"   -- QuickCache (with mutability)?
-- add them to a CommitManager AFTER they have been created (to allow multiple mutable references)? 
-- to incrementally change them requires cloning to get a mutable reference (e.g., via make_mut)?
-- but then how do deal with "dangling references" i.e., stitching the references back together again?
2. How to "find" previously staged holons (which may have been persisted in a prior session). -- Lookup by "Key"
3. Should we use quick_cache for the StagedCollection? ANSWER: No.
4.
