### ISSUE TITLE
Introduce and test HolonNode

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#4]
This issue introduces a split between the structures of the Integrity Layer and the structures of the Coordinator Layer. Specifically, it wraps the HolonNode structure at Integrity layer behind Holon structure at Coordinator Layer.

This is the initial step in bootstrapping the Holons capabilities.

### Functionality:

- "Builder-like" API, with Holon serves as a Builder for HolonNode.
- Holon only supports `PropertyMap` (i.e., no Descriptors, no Relationships, no Dances, no HolonSpace)
- Virtually no validation, since there are no Descriptors to drive validation
- hdk_extern functions:
  - `new_holon` -- creates a new (empty) Holon (does not persist anything to the DHT)
  - `add_property_value` -- adds a value for a specified property
  - `remove_property_value` -- removes a value for a specified property
  - `commit` -- commits the changes staged in a holon to the DHT
    - creates a HolonNode and SmartLinks if state = New,
    - updates the HolonNode and SmartLinks if state = Changed, _(future issue)_
    - and just returns the Holon unchanged if state = Fetched,
  -  `get_holon` -- fetches a previously persisted holon via its id, and stages it for editing
  -  `delete_holon` -- marks a previously persisted holon as deleted

### Tasks

- [x] Scaffold HolonNode with PropertyMap.
- [x] Expose hdk_extern interface
- [x] Establish initial sweetest approach for Holons.
- [x] Create HolonDescriptor in test data fixtures.

**Comment by evomimic** [comment]
In the version pushed to this branch, I have commented out the calls to `get_all_holons` in my `holon_tests.rs` file. But if I uncomment lines 66-86,  and run the tests, I get the following error:

`panicked at 'Couldn't deserialize zome call output: Deserialize("wrong msgpack marker FixArray(0)")',`

It appears that the call is never making it to my extern function.
