### ISSUE TITLE
Relocatable StagedReferences

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#51]
### Background
In our current design, CommitManager that owns holons being staged:

```
pub struct CommitManager {
    staged_holons: Vec<Rc<RefCell<Holon>>>, // Contains all holons staged for commit
    index: HashMap<MapString, usize>, // Allows lookup by key to staged holons for which keys are defined
}

```
Relationships are expressed using StagedReferences:
```
pub struct StagedReference {
    pub key : Option<MapString>,
    pub rc_holon : Rc<RefCell<Holon>>,
}

```
Since Conductor guests are stateless, I realized we need to ship the staged objects and relationships back and forth between our javascript clients and rust server until we reach a commit point. Serializing the CommitManager and StagedReferences under the current design feels problematic.

### Proposed Change
Change the design to make it more easily relocatable. Specifically, change StagedReference so that it refers to its staged holon via an integer index into the CommitManager's holons vector. 
```
pub struct StagedReference {
    pub key: Option<MapString>,
    pub holon_index: usize, // Index into the CommitManager's holons vector
}
```

### Tasks:

- [x] Change the StagedReference definition
- [x] Modify the implementation of StagedReference functions to use index instead of Rc<RefCell<<Holon>>
- [x] Adjust CommitManager to ensure staged holons are not moved or removed from its holons vector. This means, for example, marking holons as deleted, rather than simply removing them from the holons vector.
- [x] Ensure sweetests pass

**Comment by evomimic** [comment]
Merged/closed
