### ISSUE TITLE
Implement and Test with_property_values Dance

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#71]
### Proposal
This enhancement delivers the capability of adding property values for an already staged holon available through the Uniform API. To reduce chattiness across the client/conductor interface and increase use case flexibility, the dance should allow multiple property values to be set in a single dance.

### Current State:

- A native `with_property_value` function already exists within the holons zome. It upserts ONE property in the holon's property_map. It is probably not necessary to enhance this method to accept multiple property values in a single call. The with_property_values_dance adapter can iterate over its input parameters and invoke the native function for each one. These are all local calls (i.e., they don't cross the conductor API boundary)
- The current definition of the `RequestBody` enum supports EITHER an index value that references a staged_holon via the `Index` variant OR a set of properties via the `Parameters` variant. For this enhancement we need both.
- This surfaces a more general issue. The DanceRequest definition is currently oriented around a flat set of "standalone" dances accessed through a single dispatch table. However, the target MAP design is oriented towards _self-describing, active holons_ . This implies a more object-oriented style where it is the holon offering the dance. Once we have HolonDescriptors, each holon type can have its own dispatch table.  For now, we can make an incremental move towards the target design by adding `offering_holon` identifier field to the DanceRequest (NOT RequestBody). But how shall we identify the holon? Commands operate on StagedHolons (identified by their index into the staged_holons vector), Queries operate on persisted holons identified by their HolonId. 

### Proposal:

Extend the definition of DanceRequest as follows:
```
pub struct DanceRequest {
    pub dance_name: MapString, // unique key within the (single) dispatch table
    pub dance_type: DanceType,  <=== NEW
    pub body: RequestBody,
    pub staging_area: StagingArea,
    //pub descriptor: Option<HolonReference>, // space_id+holon_id of DanceDescriptor

}

```
And the definition of DanceType:
```
pub enum DanceType {
    Standalone, // i.e., a dance not associated with a specific holon
    QueryMethod(HolonId), // a read-only dance originated from a specific, already persisted, holon
    Command(StagedIndex), // a mutating method operating on a specific staged_holon identified by its index into the staged_holons vector
}
```

Since `with_property_values` is a mutator, it's DanceRequest should be of type `Command` with its staged_holon's index passed via the Command's `StagedIndex` element. This allows the set of properties being added to the staged_holon to be be passed via a `Parameters` body.

### Tasks:

- [x] Enhance definition of DanceRequest and DanceType as noted above and fix ripple effects of this change
- [x] Implement `build_with_properties_dance_request`  within `holon_dance_adapter.rs` as a CommandMethod
- [x] Implement `with_properties_dance` within holon_dance_adapter.rs, this should iteratively call native function for each property in its input property_map
- [x] Add "with_properties" dance to the Dancer's dispatch table
- [x] Add "test_with_properties_command" test step executor
- [x] Add `WithProperties` as a variant in the `DanceTestStep` enum definition and add its fmt::Display implementation
- [x] Add `add_with_properties_dance_step" function to the implementation for `DancesTestCase`
- [x] Add match that executes `WithProperties` step to dance_tests.rs
- [x] Add this step to the `simple_create_test_fixture` test case implementation (test both single property, and multi-property usages).

### Definition of Done:
- [x] After adding `with_property_values_test_steps` to the `simple_undescribed_create_holon_test`, test case **passes**

**Comment by evomimic** [comment]
Implemented and tested... will be fixed in branch #36 once PR #72 is merged.
