### ISSUE TITLE
Start implementing get_related_holons query

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-holons#84]
# NOTE: THIS ISSUE HAS CHANGED SINCE ITS ORIGINAL DEFINITION

The original title of this issue was **_Implement get_related_holons query_** and implementation was begun in branch 84. However, as the implementation scope, grew a different path to implementation seemed preferable.

## Proposal

- Define finer-grained issues that the _get_related_holons dance_ depends on. 
- Define a new issue that will complete the implementation of this query dance AFTER dependencies have been satisfied. 
- After confirming the implementation work that had already begun does not break anything (all sweetest cases still pass), merge branch 84 into main

## Tasks

- [x] Rename this issue to "_Start implementing get_related_holons query_"
- [x] Define finer-grained issues that the _get_related_holons dance_ depends on. 
     - [x] Issue #105
     - [x] Issue #106
- [x] Define a new issue that will complete the implementation of this query dance AFTER dependencies have been satisfied (DONE: See Issue #107)
- [ ] After confirming the implementation work that had already begun does not break anything (all sweetest cases still pass), file a PR to merge this branch into `main` 
- [ ] Delete branch 84
- [ ] Close issue 84

Following closure of this issue:
- Begin implementing (and merging into `main`) the dependent issues first
- Create the branch for Issue #107 only  AFTER all dependencies have been met.

**Comment by dauphin3** [comment]
this branch is up to date with main, therefore closing.
